apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: guestbook-auto
  namespace: argocd
spec: 
  destination: 
    namespace: guestbook-auto
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: guestbook
    repoURL: "https://github.com/mabusaa/argocd-example-apps.git"
    targetRevision: master # branch  
  syncPolicy:
    automated: # this automated field has been added for auto prune and auto selfHeal 
      selfHeal: true 
      prune: true 
    syncOptions:
      - CreateNamespace=true
