apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: replace01
  namespace: argocd
spec: 
  destination: 
    namespace: test-ns-1
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: sync-options/replace
    repoURL: "https://github.com/aditya-tanwar/private-argo.git"
    targetRevision: master # branch  
  syncPolicy:
    automated:
      selfHeal: true 
      prune: true 
    syncOptions:
      - CreateNamespace=true
      # - Replace=true # either replace=true can be added here in this manifest or at the k8s manifests level